package com.smollvile.fabcardview.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.smollvile.fabcardview.dao.Notes;

import com.smollvile.fabcardview.dao.NotesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig notesDaoConfig;

    private final NotesDao notesDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        notesDaoConfig = daoConfigMap.get(NotesDao.class).clone();
        notesDaoConfig.initIdentityScope(type);

        notesDao = new NotesDao(notesDaoConfig, this);

        registerDao(Notes.class, notesDao);
    }
    
    public void clear() {
        notesDaoConfig.clearIdentityScope();
    }

    public NotesDao getNotesDao() {
        return notesDao;
    }

}
