package com.smollvile.fabcardview.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "NOTES".
*/
public class NotesDao extends AbstractDao<Notes, Long> {

    public static final String TABLENAME = "NOTES";

    /**
     * Properties of entity Notes.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property TxtNotes = new Property(1, String.class, "txtNotes", false, "TXT_NOTES");
        public final static Property TxtDate = new Property(2, String.class, "txtDate", false, "TXT_DATE");
    }

    private DaoSession daoSession;


    public NotesDao(DaoConfig config) {
        super(config);
    }
    
    public NotesDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NOTES\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TXT_NOTES\" TEXT," + // 1: txtNotes
                "\"TXT_DATE\" TEXT);"); // 2: txtDate
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NOTES\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Notes entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String txtNotes = entity.getTxtNotes();
        if (txtNotes != null) {
            stmt.bindString(2, txtNotes);
        }
 
        String txtDate = entity.getTxtDate();
        if (txtDate != null) {
            stmt.bindString(3, txtDate);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Notes entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String txtNotes = entity.getTxtNotes();
        if (txtNotes != null) {
            stmt.bindString(2, txtNotes);
        }
 
        String txtDate = entity.getTxtDate();
        if (txtDate != null) {
            stmt.bindString(3, txtDate);
        }
    }

    @Override
    protected final void attachEntity(Notes entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Notes readEntity(Cursor cursor, int offset) {
        Notes entity = new Notes( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // txtNotes
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // txtDate
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Notes entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTxtNotes(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTxtDate(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Notes entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Notes entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Notes entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
